### ISSUE TITLE
safari open from terminal fails on macOS 10.14.2

### ISSUE THREAD

**Issue by avsm** [dbuenzli/webbrowser#6]
```
$ odig browse online-doc odig
450:513: execution error: Error on line 13: Error: Can't get object. (-1728)
odig: [ERROR] show uri https://erratique.ch/software/odig/doc: safari jxa: cmd ['/usr/bin/osascript' '-l' 'JavaScript' '-' 'false' 'false' 'https://erratique.ch/software/odig/doc']: 
exited [1]
```

It appears [that activating accessibility](https://apple.stackexchange.com/questions/291574/osascript-is-not-allowed-assistive-access-1728) may fix this (but doesn't for my local setup).  Creating this issue as you may want to trap this exception and point the user to those options if they work for others.

**Comment by dbuenzli** [comment]
Thanks for the report, `odig` no longer uses `webbrowser`. I responded and filed the issue there https://github.com/b0-system/b0/issues/1
